### ISSUE TITLE
Can't find `std_oak_header.h`

### ISSUE THREAD

**Issue by lemonlambda** [jorbDehmel/oak#2]
![20231230_13h11m13s_grim](https://github.com/jorbDehmel/oak/assets/55360995/04a7ffea-030b-4522-a1aa-7feeeadac84a)

**Comment by jorbDehmel** [comment]
It could be an issue w/ the path not being fully qualified? Try it now, I've updated it

**Comment by lemonlambda** [comment]
> It could be an issue w/ the path not being fully qualified? Try it now, I've updated it

It worked!
