### ISSUE TITLE
Bug (I assume) when writing if statement.

### ISSUE THREAD

**Issue by lemonlambda** [jorbDehmel/oak#4]
```rs
package!("std");
use_rule!("std");

let main() -> i32 
{
	let one: u8 = 1;
	if (one != to_u8(1) == false)
	{
		print("Worked!\n");
	}
}
```
Will compile.
```rs
package!("std");
use_rule!("std");

let main() -> i32 
{
	let one: u8 = 1;
	if ((one != to_u8(1)) == false)
	{
		print("Worked!\n");
	}
}
```
Will not compile.

**Comment by lemonlambda** [comment]
I'm going to go through the code and investigate.

**Comment by jorbDehmel** [comment]
Looks like it was an error in the operator substitution stage (see op_sub.cpp) where it was falsely identifying a function call in complex nested parenthesis statements. I'll push a bug fix in a moment!
