### ISSUE TITLE
Massive Memory Leak

### ISSUE THREAD

**Issue by lemonlambda** [jorbDehmel/oak#6]
```rs
// main.oak
package!("std");
use_rule!("std");

include!("linked_list.oak");

let main() -> i32
{
    0
}
```
```rs
// linked_list.oak
package!("std");
use_rule!("std");

let linked_list<t> = struct
{
    next: ^linked_list<t>,
    data: t
}
```
Causes a giant memory leak (4gb at least).

**Comment by lemonlambda** [comment]
![20231231_23h44m38s_grim](https://github.com/jorbDehmel/oak/assets/55360995/953262c0-d438-4196-967f-3d3675dae411)
(I have 32gb of ram and it kept growing)

**Comment by jorbDehmel** [comment]
How interesting!

The syntax for structs is a colon, not an equals.

```rust
let linked_list<t>: struct
{
    ,
}
```

That'll stop the memory leak, but I have no idea why it could be. It seems to be with that syntax issue on templated structs specifically. I'll dig into that.
